### ISSUE TITLE
Ansible to automate the deployment and configuration of a web application on multiple remote servers

### ISSUE THREAD

**Issue by jyothymolvt** [jyothymolvt/Ansible#2]
This project uses Ansible to automate the deployment and configuration of Nginx web servers on multiple remote hosts, specifically two EC2 instances. The Ansible inventory defines the target hosts grouped under [webservers], with connection details including IP addresses, SSH users, and private key files.

- The myfirstplaybook.yaml playbook performs the following tasks on all servers in the webservers group:
- Installs Nginx, using the appropriate package manager based on the target OS family (APT for Debian/Ubuntu, YUM for RedHat/CentOS/Amazon Linux).
- Copies a custom index.html file from the control node to the web root directory /var/www/html/index.html on the remote servers.

**file : /etc/ansible/hosts**

```
[webservers]

ec2-server1 ansible_host=13.203.102.47 ansible_user=ubuntu ansible_ssh_private_key_file=/home/tech/my-aws.pem
ec2-server2 ansible_host=3.109.184.139 ansible_user=ubuntu ansible_ssh_private_key_file=/home/tech/my-aws.pem

```

**file: index.html**

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to My Website</title>
</head>
<body>
<h1>Hello from Ansible deployed Nginx!</h1>
</body>
</html>

```

**myfirstplaybook.yaml** 
```
---
- name: "Myfirstplaybook"
  hosts: webservers
  become: true
  tasks:
    - name: "Install nginx"
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install Nginx (RedHat/CentOS/Amazon)"
      yum:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: "Copy index file"
      copy:
         src: index.html
         dest: /var/www/html/index.html
         owner: www-data
         group: www-data
         mode: '0644'

```

**Command: ansible-playbook myfirstplaybook.yaml** 

```
PLAY [Myfirstplaybook] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
[WARNING]: Platform linux on host ec2-server1 is using the discovered Python interpreter at /usr/bin/python3.12, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information.
ok: [ec2-server1]
[WARNING]: Platform linux on host ec2-server2 is using the discovered Python interpreter at /usr/bin/python3.12, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information.
ok: [ec2-server2]

TASK [Install nginx] *************************************************************************************************************************************************************************************************************************
changed: [ec2-server2]
changed: [ec2-server1]

TASK [Install Nginx (RedHat/CentOS/Amazon)] **************************************************************************************************************************************************************************************************
skipping: [ec2-server1]
skipping: [ec2-server2]

TASK [Copy index file] ***********************************************************************************************************************************************************************************************************************
changed: [ec2-server1]
changed: [ec2-server2]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ec2-server1                : ok=3    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
ec2-server2                : ok=3    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

```
